source 'https://rubygems.org'

# I could use the gemspec method to load the gemspec
# but hell, I gotta rewrite it anyway, so why bother.
gem 'ppt', path: '/webs/ppt/gems/ppt'

group(:development, :test) do
  gem 'pry'
end

group(:test) do
  gem 'bunny'
  gem 'rspec'

  # If Rubinius cannot find Psych it fallbacks to Syck,
  # an old, unmaintained YAML parser written by _why.
  # Syck is giving me a syntax error when I chuck the
  # Jira JSON into the document.
  gem 'psych'
end
