source 'https://rubygems.org'

gem 'ppt', path: '/webs/ppt/gems/ppt'

# This is a dependency of ppt. We can leave it up to RubyGems
# to handle it, but then we'd have to create a new release
# and run bundle update every time we'd want to update the
# code.
#
# Local overrides through bundle config local.GEMNAME don't work
# either if the gem is specified in ppt.gemspec rather than in here.
gem 'pipeline.rb', github: 'botanicus/pipeline.rb', branch: 'master'

group(:development, :test) do
  gem 'pry'
end

group(:test) do
  gem 'bunny'
  gem 'rspec'

  # If Rubinius cannot find Psych it fallbacks to Syck,
  # an old, unmaintained YAML parser written by _why.
  # Syck is giving me a syntax error when I chuck the
  # Jira JSON into the document.
  gem 'psych'
end
