source 'https://rubygems.org'

gem 'amq-client'

gem 'redis'
gem 'hiredis'

group(:development, :test) do
  gem 'pry'
end

group(:test) do
  gem 'bunny'
  gem 'rspec'

  # If Rubinius cannot find Psych it fallbacks to Syck,
  # an old, unmaintained YAML parser written by _why.
  # Syck is giving me a syntax error when I chuck the
  # Jira JSON into the document.
  gem 'psych'
end
