# https://github.com/cucumber/cucumber/wiki/cucumber.yml
smoke: SITE=pay-per-task.com --tags @smoke
wip: --tags @wip
CI: CI=true SCREENSHOT_DIR=<%= ENV['CIRCLE_ARTIFACTS'] %>/<%= ENV['BROWSER'] || 'phantomjs' %> --format html --out <%= ENV['CIRCLE_ARTIFACTS'] %>/features<%= "_#{ENV['BROWSER']}" if ENV['BROWSER'] %>.html
