NAME = File.basename(Dir.pwd)
PATH = "/webs/#{NAME}"

desc "Build and run the container."
task default: ['docker:build', 'docker:run']

# Services do run in Docker, but the integration tests don't have to.
# Unit: docker run myimage bundle exec rake test
namespace :ci do
  task build: ['docker:build'] do
    # TODO: Haproxy -> API & this.
    # TODO: Installing protractor will take ages.
    # PhantomJS headless
    # Create a Dockerfile in Test and create a new layer with the testing tools?
    #   ... does it help?
    sh "docker run -d -p 80:80 #{NAME}"
    Dir.chdir('content') do
      sh "bower install"
    end

    # Setup.
    sh "npm install protractor"
    sh "webdriver-manager update"

    # Tests.
    fork { sh "webdriver-manager start" }
    sleep 2.5 # Catch up with webdriver
    puts "~ Running the tests."
    sh "./protractor.conf.js"

    # TODO: Run the tests.
    # Not necessary I guess?
    # sh <<-EOF
    #   for container in $(docker ps | awk '{ print $1 }'); do
    #     test $container '!=' CONTAINER && docker kill $container
    #   done
    # EOF
    # TODO: Trigger Dockerhub build just for this repo.
    # - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
    # - docker push circleci/elasticsearch
  end
end

desc "Open the running site."
task :open do
  ip = %x{boot2docker ip}
  sh "open http://#{ip}"
end

namespace :docker do
  desc "Build the image."
  task :build do
    sh "docker build -t #{NAME} ."
  end

  desc "Run the container."
  task :run do
    sh "docker run -d -p 80:80 -v #{Dir.pwd}:#{PATH}:ro #{NAME}"
    api_ppt_path = File.join(File.dirname(PATH), 'api.pay-per-task.com')
    sh "docker run -d -p 80:80 -v #{api_ppt_path}:/webs/api.pay-per-task.com:ro api.pay-per-task.com"
  end

  desc "SSH into a running container."
  task :ssh do
    id = %x{docker ps | grep #{NAME}:latest | awk '{ print $1 }'}.chomp
    sh "docker exec -it #{id} /bin/sh"
  end

  desc "Publish the image."
  task :publish do
    # TODO
  end
end
