NAME = File.basename(Dir.pwd)
PATH = "/webs/#{NAME}"

desc "Build and run the container."
task default: ['docker:build', 'docker:run']

# Services and unit tests run in Docker.
# Integration tests runs ON the CI AGAINST the containers.
namespace :ci do
  task :build do
    #
  end
end

desc "Open the running site."
task :open do
  ip = %x{boot2docker ip}
  sh "open http://#{ip}"
end

namespace :docker do
  desc "Build the image."
  task :build do
    sh "docker build -t #{NAME} ."
  end

  desc "Run the container."
  task :run do
    sh "docker run -d -p 80:80 -v #{Dir.pwd}:#{PATH}:ro #{NAME}"
    api_ppt_path = File.join(File.dirname(PATH), 'api.pay-per-task.com')
    sh "docker run -d -p 80:80 -v #{api_ppt_path}:/webs/api.pay-per-task.com:ro api.pay-per-task.com"
  end

  desc "SSH into a running container."
  task :ssh do
    id = %x{docker ps | grep #{NAME}:latest | awk '{ print $1 }'}.chomp
    sh "docker exec -it #{id} /bin/sh"
  end

  desc "Publish the image."
  task :publish do
    # TODO
  end
end
