# encoding: utf-8

# Run: bundle exec guard

guard(:nanoc) do
  watch('nanoc.yaml')
  watch('Rules')
  watch(%r{^(content|layouts|lib)/.*$})
end

# This doesn't work now, dunno why, but fuck it.
# guard(:shell) do
#   watch('crash.log') do |path, basename|
#     system "rm #{path}"
#   end
# end
