source 'https://rubygems.org'

gem 'rack'
gem 'puma'

gem 'redis'
gem 'hiredis'

gem 'bunny'

group(:test) do
  gem 'ppt', path: '/webs/ppt/gems/ppt'
  gem 'rspec'
  gem 'rspec-sane-http', github: 'botanicus/rspec-sane-http', branch: 'master'
end
